#!/usr/bin/env python3
"""Generate (or --check) policies/<name>/artifacthub-pkg.yml for every Kyverno policy.

Metadata comes from the policy annotations; `digest` is the sha256 of the policy file, so
Artifact Hub publishes a new version whenever the policy changes (bump VERSION too).
Standard library only.
"""
import hashlib
import pathlib
import re
import sys

REPO = "https://github.com/Fractal-Techware/kubernetes-hardening-baseline"
RAW = "https://raw.githubusercontent.com/Fractal-Techware/kubernetes-hardening-baseline/main"
VERSION = "1.0.0"
CREATED_AT = "2026-09-17T00:00:00Z"
KYVERNO_VERSION = "1.19"
K8S_VERSION = "1.32-1.37"
ROOT = pathlib.Path(__file__).resolve().parent.parent


def annotation(text: str, key: str) -> str:
    # Supports single-line values and folded (>-) block scalars.
    m = re.search(rf"^    {re.escape(key)}: >-\n((?:      .*\n)+)", text, re.M)
    if m:
        return " ".join(line.strip() for line in m.group(1).splitlines())
    m = re.search(rf"^    {re.escape(key)}: (.+)$", text, re.M)
    if not m:
        sys.exit(f"missing annotation {key}")
    return m.group(1).strip()


def render(policy: pathlib.Path) -> str:
    text = policy.read_text()
    name = policy.stem
    title = annotation(text, "policies.kyverno.io/title")
    desc = annotation(text, "policies.kyverno.io/description")
    category = annotation(text, "policies.kyverno.io/category")
    severity = annotation(text, "policies.kyverno.io/severity")
    subject = annotation(text, "policies.kyverno.io/subject")
    digest = hashlib.sha256(policy.read_bytes()).hexdigest()
    return f"""# Generated by scripts/gen_artifacthub.py. Do not edit by hand.
name: {name}
version: {VERSION}
displayName: {title}
createdAt: "{CREATED_AT}"
description: >-
  {desc}
license: MIT
homeURL: {REPO}
keywords:
  - kyverno
  - kubernetes
  - security
  - {category.lower().replace(' ', '-')}
  - validatingpolicy
  - cel
provider:
  name: Fractal Techware
links:
  - name: source
    url: {REPO}/tree/main/policies/{name}
  - name: tests
    url: {REPO}/tree/main/policies/{name}/.kyverno-test
install: |-
  ```shell
  kubectl apply -f {RAW}/policies/{name}/{name}.yaml
  ```
readme: |
  # {title}

  {desc}

  - Severity: **{severity}**
  - Engine: Kyverno {KYVERNO_VERSION}+ `ValidatingPolicy` (CEL), autogen for Deployments, StatefulSets, DaemonSets, Jobs and CronJobs
  - Mode: ships in **Audit** (report only). Switch to Deny after reviewing PolicyReports.
  - Tested: passing and failing resources under `.kyverno-test/`, run with `kyverno test`.

  Part of the free [Kubernetes Hardening Baseline]({REPO}) by Fractal Techware.
annotations:
  kyverno/category: "{category}"
  kyverno/kubernetesVersion: "{K8S_VERSION}"
  kyverno/subject: "{subject}"
  kyverno/version: "{KYVERNO_VERSION}"
digest: {digest}
"""


def main() -> int:
    check = "--check" in sys.argv
    stale = []
    for policy in sorted(ROOT.glob("policies/*/*.yaml")):
        if policy.parent.name != policy.stem:
            continue
        out = policy.parent / "artifacthub-pkg.yml"
        content = render(policy)
        if check:
            if not out.exists() or out.read_text() != content:
                stale.append(str(out.relative_to(ROOT)))
        else:
            out.write_text(content)
            print(f"wrote {out.relative_to(ROOT)}")
    if stale:
        print("stale artifacthub-pkg.yml (run scripts/gen_artifacthub.py):", *stale, sep="\n  ")
        return 1
    if check:
        print("artifacthub-pkg.yml files are up to date")
    return 0


if __name__ == "__main__":
    sys.exit(main())
